site_name: Fanily
site_url: http://fanily.algobet.xyz/
site_description: Fanily Group
site_author: The Fanily

repo_url: https://github.com/algobet/fanily.clover

pages:
  - Home: index.md
  - Isaac: isaac.md

copyright: Copyright &copy; 2017 <a href="https://twitter.com/algobet_xyz">algobet&trade; concept</a>

theme_dir: mkdocs_bootstrap
